data_path: journal/all/data_train-ticket
figure_path: journal/all/data_train-ticket/figures
yaml_repo_path: yamlRepository/trainTicket
namespace: train-ticket
app_img: nicklin9907/erms:trainticket-1.0
nodes_for_test:
- slave9
- slave15
- slave17
prometheus_host: http://localhost:30091
nodes_for_infra:
- slave9
- slave15
- slave17
pod_spec:
  cpu_size: 200m
  mem_size: 1Gi

replicas:
  Query:
    ts-travel-service: 5
    ts-config-service: 5
    ts-basic-service: 5
    ts-station-service: 5
    ts-order-service: 5
    ts-route-service: 5
    ts-seat-service: 5
    ts-ticketinfo-service: 5