repeats: [8, 9]
duration: 40
services: 
- Query
interference_config:
  cpu:
    cpu_size: 1
    mem_size: 10Mi
    pod_range: [2]
  capacity:
    cpu_size: 0.01
    mem_size: 4Gi
    pod_range: [7]
  bandwidth:
    cpu_size: 1
    mem_size: 100Mi
    pod_range: [9]
  network:
    cpu_size: 0.1
    mem_size: 200Mi
    throughput: 200Mi
    pod_range: [2]
workload_config:
  wrk_path: wrk2/wrk
  services:
    Query:
      max_clients: 20
      thread_num: 1
      connection_num: 2
      throughput: 1
      script_path: wrk2/scripts/train-ticket/query.lua
      url: http://localhost:32677
collector_config:
  jaeger_host: http://localhost:32688
  entry_point: ts-basic-service
  max_traces: 200
  monitor_interval: 1